<?php


namespace app\facade;


use think\Facade;

class Test extends Facade
{
   public static function getFacadeClass()
   {
//       parent::getFacadeClass(); // TODO: Change the autogenerated stub
       return 'app\common\Test';
   }
}